import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Analytics Page",
  description: "Generated by create next app",
};

export default function Analytics() {
  return (
    <div className="flex align-center justify-center min-h-screen bg-blue-100 p-8">
      <h1 className="text-2xl font-bold">Analytics</h1>
    </div>
  );
}
