import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CustomLink from "./components/CustomLink";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("RootLayout loaded");
  const arr = [1, 2, 3];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex flex-col justify-between items-center p-4 bg-gray-800 text-white">
          <ul className="flex space-x-4 p-4">
            {arr.map((item) => (
              <li key={item}>
                <CustomLink path={`/dashboard/${item}`}>{`Item ${item}`}</CustomLink>
              </li>
            ))}
            <li>
              <CustomLink path="/home">Home</CustomLink>
            </li>
            <li>
              <CustomLink path="/dashboard/analytics">Analytics</CustomLink>
            </li>
            <li>
              <CustomLink path="/dashboard/settings">Settings</CustomLink>
            </li>
            <li>
              <CustomLink path="/contact">Contact</CustomLink>
            </li>
          </ul>
        </nav>
        <>{children}</>
      </body>
    </html>
  );
}
