import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("RootLayout loaded");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex flex-col justify-between items-center p-4 bg-gray-800 text-white">
          <ul className="flex space-x-4 p-4">
            <li><Link href="/home">Home</Link></li>
            <li><Link href="/dashboard/analytics">Analytics</Link></li>
            <li><Link href="/dashboard/settings">Settings</Link></li>
            <li><Link href="/contact">Contact</Link></li>
          </ul>
        </nav>
        <>
        {children}
        </>
      </body>
    </html>
  );
}
