import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard Page",
  description: "Generated by create next app",
};

export default function Dashboard() {
  return (
    <div className="flex align-center justify-center min-h-screen bg-red-100 p-8">
      <h1 className="text-2xl font-bold">Dashboard</h1>
    </div>
  );
}
